spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: library-manager-api
  threads:
    virtual:
      enabled: true
  profiles:
    active: dev
jwt:
  public:
    key: classpath:app.pub
  private:
    key: classpath:app.key
  expiration-time: 3600